apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-rollout
spec:
  replicas: 10
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 20s
      - setWeight: 20
      - pause:
          duration: 20s
      - setWeight: 30
      - pause:
          duration: 320s
      - setWeight: 40
      - pause:
          duration: 20s
      - setWeight: 50
      - pause:
          duration: 20s
