apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mglaserde/knowledge_transfer
    path: Deployments/blue-green
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: bluegreen
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
