apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mglaserde/knowledge_transfer
    path: Deployments/canary
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
